server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    gateway:
      routes:
        - id: user-microservice
          uri: http://localhost:8001/
          predicates:
            - Path=/users/**
        - id: department-microservice
          uri: http://localhost:8002/
          predicates:
            - Path=/departments/**
    config:
      server:
        git:
          uri: https://github.com/NguyenVVLap/cloud-config-server-user-department
          default-label: main
        bootstrap: false